### ISSUE TITLE
Unable to sync, cannot find contact folder

### ISSUE THREAD

**Issue by jussihi** [JeshuaEdgar/gal-sync-graph#3]
**Describe the bug**
When trying to sync a defined list of contacts, it seems like the program "cannot find" the contact folder for a user.

**To Reproduce**
Sync a list containing 1 user

**Expected behavior**
The program would happily sync the user's GAL list to a named contact folder IIUC

**Logs**
```
VERBOSE: Loading module from path
'C:\Users\jussi.hietanen\Downloads\gal-sync-graph-master\gal-sync-graph-master\Module\GAL-Sync.psm1'.
VERBOSE: Loading module GAL-Sync...
VERBOSE: Creating modules variables...
VERBOSE: Exporting function 'Connect-GALSync'.
VERBOSE: Exporting function 'Get-GALAADGroupMembers'.
VERBOSE: Exporting function 'Get-GALContacts'.
VERBOSE: Exporting function 'New-GraphRequest'.
VERBOSE: Exporting function 'Sync-GALContacts'.
VERBOSE: Exporting function 'Write-LogEvent'.
VERBOSE: Exporting function 'Write-VerboseEvent'.
VERBOSE: Exporting function 'Get-ContactFolder'.
VERBOSE: Exporting function 'New-ContactFolder'.
VERBOSE: Exporting function 'Get-FolderContact'.
VERBOSE: Exporting function 'New-FolderContact'.
VERBOSE: Exporting function 'Remove-FolderContact'.
VERBOSE: Exporting function 'Update-FolderContact'.
VERBOSE: Importing function 'Connect-GALSync'.
VERBOSE: Importing function 'Get-ContactFolder'.
VERBOSE: Importing function 'Get-FolderContact'.
VERBOSE: Importing function 'Get-GALAADGroupMembers'.
VERBOSE: Importing function 'Get-GALContacts'.
VERBOSE: Importing function 'New-ContactFolder'.
VERBOSE: Importing function 'New-FolderContact'.
VERBOSE: Importing function 'New-GraphRequest'.
VERBOSE: Importing function 'Remove-FolderContact'.
VERBOSE: Importing function 'Sync-GALContacts'.
VERBOSE: Importing function 'Update-FolderContact'.
VERBOSE: Importing function 'Write-LogEvent'.
VERBOSE: Importing function 'Write-VerboseEvent'.
VERBOSE: POST with -1-byte payload
VERBOSE: received 1732-byte response of content type application/json; charset=utf-8
VERBOSE: 2023.11.01 09.53.08 | Verbose | Permissions are OK!
True
VERBOSE: 2023.11.01 09.53.08 | Verbose | Getting GAL contacts
VERBOSE: 2023.11.01 09.53.08 | Verbose | Parameter : Method
VERBOSE: 2023.11.01 09.53.08 | Verbose | Value     : Get
VERBOSE: 2023.11.01 09.53.08 | Verbose | Parameter : Content-Type
VERBOSE: 2023.11.01 09.53.08 | Verbose | Value     : application/json
VERBOSE: 2023.11.01 09.53.08 | Verbose | Parameter : Authorization
VERBOSE: 2023.11.01 09.53.08 | Verbose | Value     : Bearer
***
LONG TOKEN
***
VERBOSE: 2023.11.01 09.53.08 | Verbose | Parameter : Headers
VERBOSE: 2023.11.01 09.53.08 | Verbose | Value     : System.Collections.Hashtable
VERBOSE: 2023.11.01 09.53.08 | Verbose | Parameter : URI
VERBOSE: 2023.11.01 09.53.08 | Verbose | Value     : https://graph.microsoft.com/beta/users?$select=*
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type
application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
VERBOSE: 2023.11.01 09.53.09 | Verbose | Found @odata.nextLink
VERBOSE: 2023.11.01 09.53.09 | Verbose |
https://graph.microsoft.com/beta/users?$select=*&$skiptoken=**SKIPTOKEN**
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type
application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type
application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type
application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type
application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type
application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type
application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
VERBOSE: 2023.11.01 09.53.13 | Verbose | 55 contacts found
2023.11.01 09.53.13 | Info | Beginning sync for @(jussi.hietanen@mydomain.com)
VERBOSE: 2023.11.01 09.53.13 | Verbose | Getting folder syncedpeople
VERBOSE: 2023.11.01 09.53.13 | Verbose | Parameter : Method
VERBOSE: 2023.11.01 09.53.13 | Verbose | Value     : Get
VERBOSE: 2023.11.01 09.53.13 | Verbose | Parameter : Content-Type
VERBOSE: 2023.11.01 09.53.13 | Verbose | Value     : application/json
VERBOSE: 2023.11.01 09.53.13 | Verbose | Parameter : Authorization
VERBOSE: 2023.11.01 09.53.13 | Verbose | Value     : Bearer
***
LONG TOKEN/PAYLOAD
***
VERBOSE: 2023.11.01 09.53.13 | Verbose | Parameter : Headers
VERBOSE: 2023.11.01 09.53.13 | Verbose | Value     : System.Collections.Hashtable
VERBOSE: 2023.11.01 09.53.13 | Verbose | Parameter : URI
VERBOSE: 2023.11.01 09.53.13 | Verbose | Value     :
https://graph.microsoft.com/beta/users/@(jussi.hietanen@mydomain.com)/contactFolders?$filter=displayName eq
'syncedpeople'
VERBOSE: GET with 0-byte payload
2023.11.01 09.53.13 | Error | Something went wrong getting the contact folder for @(jussi.hietanen@mydomain.com)
2023.11.01 09.53.13 | Error | Failed to sync mailbox: @(jussi.hietanen@mydomain.com)
```

**Desktop (please complete the following information):**
 - Windows
 - Powershell 5.1

I'm invoking the script with a following BAT file:

```
@echo off

PowerShell.exe -ExecutionPolicy Bypass ^
-File "%CD%\Sync-Contacts.ps1" ^
-CredentialPath "%CD%\Credentials\credential.cred" ^
-Tenant "***" ^
-ContactFolderName "syncedpeople" ^
-LogPath "%CD%\Logs" ^
-Verbose ^
-MailboxList @("jussi.hietanen@mydomain.com")
pause
```

What is going wrong?

**Comment by jussihi** [comment]
And as a general note I also would like to thank you a lot for your effort on this repo, this is something that really should be built-in in m365...

**Comment by JeshuaEdgar** [comment]
Hi Jussi, 

Thanks and I agree. 

Can you try just `-MailboxList "jussi.hietanen@mydomain.com"` instead of `-MailboxList @("jussi.hietanen@mydomain.com")` the @() denotes a list, PowerShell is a little goofy when it comes to input like that sometimes.  I will have a look if the bug is reproduced when it comes to an actual list.

Let met know if that fixes your issue!

**Comment by jussihi** [comment]
> Hi Jussi,
> 
> Thanks and I agree.
> 
> Can you try just `-MailboxList "jussi.hietanen@mydomain.com"` instead of `-MailboxList @("jussi.hietanen@mydomain.com")` the @() denotes a list, PowerShell is a little goofy when it comes to input like that sometimes. I will have a look if the bug is reproduced when it comes to an actual list.
> 
> Let met know if that fixes your issue!

Thanks for the quick reply @JeshuaEdgar !

Unfortunately, changing list to a single contact didn't help - I still get the same error.

Should I create this "syncedpeople" folder to my test user's contacts before running the script or should this script create it for me? I would prefer the latter if I'm going to run this against all the people belonging to my org

**Comment by jussihi** [comment]
Just to make sure, aren't the API permissions meant to be set as follows?
![image](https://github.com/JeshuaEdgar/gal-sync-graph/assets/25184163/14962877-cfde-49e0-9836-4eac87fee1bf)

**Comment by jussihi** [comment]
It seems like I get more output when reading the actual logfile. Here is the logfile for your inspection:
```
**********************
Windows PowerShell transcript start
Start time: 20231101102824
Username: LOCALDOMAIN\jussi.hietanen
RunAs User: LOCALDOMAIN\jussi.hietanen
Configuration Name: 
Machine: WK390 (Microsoft Windows NT 10.0.22621.0)
Host Application: PowerShell.exe -ExecutionPolicy Bypass -File C:\Users\jussi.hietanen\Downloads\gal-sync-graph-master\gal-sync-graph-master\Sync-Contacts.ps1 -CredentialPath C:\Users\jussi.hietanen\Downloads\gal-sync-graph-master\gal-sync-graph-master\Credentials\credential.cred -Tenant **TENANT** -ContactFolderName syncedpeople -LogPath C:\Users\jussi.hietanen\Downloads\gal-sync-graph-master\gal-sync-graph-master\Logs -Verbose -MailboxList jussi.hietanen@mydomain.com
Process ID: 7872
PSVersion: 5.1.22621.2428
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2428
BuildVersion: 10.0.22621.2428
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
VERBOSE: Loading module from path 'C:\Users\jussi.hietanen\Downloads\gal-sync-graph-master\gal-sync-graph-master\Module\GAL-Sync.psm1'.
VERBOSE: Loading module GAL-Sync...
VERBOSE: Creating modules variables...
VERBOSE: Exporting function 'Connect-GALSync'.
VERBOSE: Exporting function 'Get-GALAADGroupMembers'.
VERBOSE: Exporting function 'Get-GALContacts'.
VERBOSE: Exporting function 'New-GraphRequest'.
VERBOSE: Exporting function 'Sync-GALContacts'.
VERBOSE: Exporting function 'Write-LogEvent'.
VERBOSE: Exporting function 'Write-VerboseEvent'.
VERBOSE: Exporting function 'Get-ContactFolder'.
VERBOSE: Exporting function 'New-ContactFolder'.
VERBOSE: Exporting function 'Get-FolderContact'.
VERBOSE: Exporting function 'New-FolderContact'.
VERBOSE: Exporting function 'Remove-FolderContact'.
VERBOSE: Exporting function 'Update-FolderContact'.
VERBOSE: Importing function 'Connect-GALSync'.
VERBOSE: Importing function 'Get-ContactFolder'.
VERBOSE: Importing function 'Get-FolderContact'.
VERBOSE: Importing function 'Get-GALAADGroupMembers'.
VERBOSE: Importing function 'Get-GALContacts'.
VERBOSE: Importing function 'New-ContactFolder'.
VERBOSE: Importing function 'New-FolderContact'.
VERBOSE: Importing function 'New-GraphRequest'.
VERBOSE: Importing function 'Remove-FolderContact'.
VERBOSE: Importing function 'Sync-GALContacts'.
VERBOSE: Importing function 'Update-FolderContact'.
VERBOSE: Importing function 'Write-LogEvent'.
VERBOSE: Importing function 'Write-VerboseEvent'.
VERBOSE: POST with -1-byte payload
VERBOSE: received 1732-byte response of content type application/json; charset=utf-8
VERBOSE: 2023.11.01 10.28.24 | Verbose | Permissions are OK!
True
VERBOSE: 2023.11.01 10.28.24 | Verbose | Getting GAL contacts
VERBOSE: 2023.11.01 10.28.25 | Verbose | Parameter : Method
VERBOSE: 2023.11.01 10.28.25 | Verbose | Value     : Get
VERBOSE: 2023.11.01 10.28.25 | Verbose | Parameter : Content-Type
VERBOSE: 2023.11.01 10.28.25 | Verbose | Value     : application/json
VERBOSE: 2023.11.01 10.28.25 | Verbose | Parameter : Authorization
VERBOSE: 2023.11.01 10.28.25 | Verbose | Value     : Bearer 
***
LONG TOKEN
***
VERBOSE: 2023.11.01 10.28.25 | Verbose | Parameter : Headers
VERBOSE: 2023.11.01 10.28.25 | Verbose | Value     : System.Collections.Hashtable
VERBOSE: 2023.11.01 10.28.25 | Verbose | Parameter : URI
VERBOSE: 2023.11.01 10.28.25 | Verbose | Value     : https://graph.microsoft.com/beta/users?$select=*
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
VERBOSE: 2023.11.01 10.28.25 | Verbose | Found @odata.nextLink
VERBOSE: 2023.11.01 10.28.25 | Verbose | https://graph.microsoft.com/beta/users?$select=*&$skiptoken=**SKIPTOKEN**
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
VERBOSE: 2023.11.01 10.28.29 | Verbose | 55 contacts found
2023.11.01 10.28.29 | Info | Beginning sync for jussi.hietanen@mydomain.com
VERBOSE: 2023.11.01 10.28.29 | Verbose | Getting folder syncedpeople
VERBOSE: 2023.11.01 10.28.29 | Verbose | Parameter : Method
VERBOSE: 2023.11.01 10.28.29 | Verbose | Value     : Get
VERBOSE: 2023.11.01 10.28.29 | Verbose | Parameter : Content-Type
VERBOSE: 2023.11.01 10.28.29 | Verbose | Value     : application/json
VERBOSE: 2023.11.01 10.28.29 | Verbose | Parameter : Authorization
VERBOSE: 2023.11.01 10.28.29 | Verbose | Value     : Bearer 
***
LONG TOKEN
***
VERBOSE: 2023.11.01 10.28.29 | Verbose | Parameter : Headers
VERBOSE: 2023.11.01 10.28.29 | Verbose | Value     : System.Collections.Hashtable
VERBOSE: 2023.11.01 10.28.29 | Verbose | Parameter : URI
VERBOSE: 2023.11.01 10.28.29 | Verbose | Value     : https://graph.microsoft.com/beta/users/jussi.hietanen@mydomain.com/contactFolders?$filter=displayName eq 'syncedpeople'
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; odata.metadata=minimal; odata.streaming=true; IEEE754Compatible=false; charset=utf-8
VERBOSE: 2023.11.01 10.28.29 | Verbose | Not able to find the contact folder syncedpeople for jussi.hietanen@mydomain.com
VERBOSE: 2023.11.01 10.28.29 | Verbose | Getting parent ID
VERBOSE: 2023.11.01 10.28.29 | Verbose | Getting folder Contacts
VERBOSE: 2023.11.01 10.28.29 | Verbose | Parameter : Method
VERBOSE: 2023.11.01 10.28.29 | Verbose | Value     : Get
VERBOSE: 2023.11.01 10.28.29 | Verbose | Parameter : Content-Type
VERBOSE: 2023.11.01 10.28.29 | Verbose | Value     : application/json
VERBOSE: 2023.11.01 10.28.29 | Verbose | Parameter : Authorization
VERBOSE: 2023.11.01 10.28.29 | Verbose | Value     : Bearer 
***
LONG TOKEN
***
VERBOSE: 2023.11.01 10.28.29 | Verbose | Parameter : Headers
VERBOSE: 2023.11.01 10.28.29 | Verbose | Value     : System.Collections.Hashtable
VERBOSE: 2023.11.01 10.28.29 | Verbose | Parameter : URI
VERBOSE: 2023.11.01 10.28.29 | Verbose | Value     : https://graph.microsoft.com/beta/users/jussi.hietanen@mydomain.com/contactFolders?$filter=displayName eq 'Contacts'
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; odata.metadata=minimal; odata.streaming=true; IEEE754Compatible=false; charset=utf-8
VERBOSE: 2023.11.01 10.28.30 | Verbose | Default contacts folder is querried
VERBOSE: 2023.11.01 10.28.30 | Verbose | Not able to find the contact folder Contacts for jussi.hietanen@mydomain.com
VERBOSE: 2023.11.01 10.28.30 | Verbose | Parent ID:
VERBOSE: 2023.11.01 10.28.30 | Verbose | Creating new folder syncedpeople
VERBOSE: 2023.11.01 10.28.30 | Verbose | Parameter : Method
VERBOSE: 2023.11.01 10.28.30 | Verbose | Value     : Post
VERBOSE: 2023.11.01 10.28.30 | Verbose | Parameter : Body
VERBOSE: 2023.11.01 10.28.30 | Verbose | Value     : {
    "displayName":  "syncedpeople",
    "parentFolderId":  {

                       }
}
VERBOSE: 2023.11.01 10.28.30 | Verbose | Parameter : Content-Type
VERBOSE: 2023.11.01 10.28.30 | Verbose | Value     : application/json
VERBOSE: 2023.11.01 10.28.30 | Verbose | Parameter : Authorization
VERBOSE: 2023.11.01 10.28.30 | Verbose | Value     : Bearer 
***
LONG TOKEN
***
VERBOSE: 2023.11.01 10.28.30 | Verbose | Parameter : Headers
VERBOSE: 2023.11.01 10.28.30 | Verbose | Value     : System.Collections.Hashtable
VERBOSE: 2023.11.01 10.28.30 | Verbose | Parameter : URI
VERBOSE: 2023.11.01 10.28.30 | Verbose | Value     : https://graph.microsoft.com/beta/users/jussi.hietanen@mydomain.com/contactFolders
VERBOSE: POST with -1-byte payload
>> TerminatingError(Invoke-RestMethod): "Etäpalvelin palautti virheen: (400) Virheellinen pyyntö."
PS>TerminatingError(): "Etäpalvelin palautti virheen: (400) Virheellinen pyyntö."
PS>TerminatingError(): "Etäpalvelin palautti virheen: (400) Virheellinen pyyntö."
>> TerminatingError(): "Something went wrong getting the contact folder for jussi.hietanen@mydomain.com"
2023.11.01 10.28.30 | Error | Something went wrong getting the contact folder for jussi.hietanen@mydomain.com
2023.11.01 10.28.30 | Error | Failed to sync mailbox: jussi.hietanen@mydomain.com
**********************
Windows PowerShell transcript end
End time: 20231101102830
**********************

```

Etäpalvelin palautti virheen: (400) Virheellinen pyyntö:
Remote server returned an error (400): Invalid request

**Comment by jussihi** [comment]
Seems like I've got it working (at least partially) after changing the hardcoded "Contacts" to Finnish "Kontaktit" in func_Get-ContactFolder.ps1:7 : `$contactsFolder = "Kontaktit"`. However, it only seems to sync contacts starting from "T". I only get 50something contacts when I should get over 600.

Also, nordic letters such as Ä, Å, and Ö are not showing up properly.

I will see if I can find a way around these issues and come back to this issue.. 👍

**Comment by jussihi** [comment]
Well running it successfully once enabled to run it successfully... just once.

It seems like outlook doesn't have contact _folders_ anymore, but instead they use some sort of categories/tags. With current code it seems like updating / removing these contacts from this newly created folder/tag does not work. I now keep getting `2023.11.01 12.56.41 | Error | Failed to remove contact` for every entry in the GAL.

Here's a snippet of the logfile now:
```
2023.11.01 12.56.39 | Info | Beginning sync for jussi.hietanen@mydomain.com
VERBOSE: 2023.11.01 12.56.39 | Verbose | Getting folder syncedpeople
VERBOSE: 2023.11.01 12.56.39 | Verbose | Parameter : Method
VERBOSE: 2023.11.01 12.56.39 | Verbose | Value     : Get
VERBOSE: 2023.11.01 12.56.39 | Verbose | Parameter : Content-Type
VERBOSE: 2023.11.01 12.56.39 | Verbose | Value     : application/json
VERBOSE: 2023.11.01 12.56.39 | Verbose | Parameter : Authorization
VERBOSE: 2023.11.01 12.56.39 | Verbose | Value     : Bearer 
***
LONG BEARER TOKEN
***
VERBOSE: 2023.11.01 12.56.39 | Verbose | Parameter : Headers
VERBOSE: 2023.11.01 12.56.39 | Verbose | Value     : System.Collections.Hashtable
VERBOSE: 2023.11.01 12.56.39 | Verbose | Parameter : URI
VERBOSE: 2023.11.01 12.56.39 | Verbose | Value     : https://graph.microsoft.com/beta/users/jussi.hietanen@mydomain.com/contactFolders?$filter=displayName eq 'syncedpeople'
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; odata.metadata=minimal; odata.streaming=true; IEEE754Compatible=false; charset=utf-8
VERBOSE: 2023.11.01 12.56.39 | Verbose | Found folder syncedpeople, returning!
2023.11.01 12.56.39 | Info | Found folder syncedpeople for jussi.hietanen@mydomain.com
VERBOSE: 2023.11.01 12.56.39 | Verbose | Parameter : Method
VERBOSE: 2023.11.01 12.56.39 | Verbose | Value     : Get
VERBOSE: 2023.11.01 12.56.39 | Verbose | Parameter : Content-Type
VERBOSE: 2023.11.01 12.56.39 | Verbose | Value     : application/json
VERBOSE: 2023.11.01 12.56.39 | Verbose | Parameter : Authorization
VERBOSE: 2023.11.01 12.56.39 | Verbose | Value     : Bearer 
***
LONG BEARER TOKEN
***
VERBOSE: 2023.11.01 12.56.39 | Verbose | Parameter : Headers
VERBOSE: 2023.11.01 12.56.39 | Verbose | Value     : System.Collections.Hashtable
VERBOSE: 2023.11.01 12.56.39 | Verbose | Parameter : URI
VERBOSE: 2023.11.01 12.56.39 | Verbose | Value     : https://graph.microsoft.com/v1.0/users/jussi.hietanen@mydomain.com/contactfolders/*contactfolder_id*/contacts?$top=999
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; odata.metadata=minimal; odata.streaming=true; IEEE754Compatible=false; charset=utf-8
VERBOSE: 2023.11.01 12.56.40 | Verbose | Found 55 contacts in the folder
VERBOSE: 2023.11.01 12.56.40 | Verbose | Parameter : Method
VERBOSE: 2023.11.01 12.56.40 | Verbose | Value     : Delete
VERBOSE: 2023.11.01 12.56.40 | Verbose | Parameter : Content-Type
VERBOSE: 2023.11.01 12.56.40 | Verbose | Value     : application/json
VERBOSE: 2023.11.01 12.56.40 | Verbose | Parameter : Authorization
VERBOSE: 2023.11.01 12.56.40 | Verbose | Value     : Bearer 
***
LONG BEARER TOKEN
***
VERBOSE: 2023.11.01 12.56.40 | Verbose | Parameter : Headers
VERBOSE: 2023.11.01 12.56.40 | Verbose | Value     : System.Collections.Hashtable
VERBOSE: 2023.11.01 12.56.40 | Verbose | Parameter : URI
VERBOSE: 2023.11.01 12.56.40 | Verbose | Value     : https://graph.microsoft.com/v1.0/users/jussi.hietanen@mydomain.com/contactFolders/**folder_id**/contacts/
VERBOSE: DELETE with 0-byte payload
>> TerminatingError(Invoke-RestMethod): "Etäpalvelin palautti virheen: (405) Menetelmä ei ole sallittu."
PS>TerminatingError(): "Etäpalvelin palautti virheen: (405) Menetelmä ei ole sallittu."
PS>TerminatingError(): "Etäpalvelin palautti virheen: (405) Menetelmä ei ole sallittu."
2023.11.01 12.56.40 | Error | Failed to remove contact
VERBOSE: 2023.11.01 12.56.40 | Verbose | Parameter : Method
VERBOSE: 2023.11.01 12.56.40 | Verbose | Value     : Delete
VERBOSE: 2023.11.01 12.56.40 | Verbose | Parameter : Content-Type
VERBOSE: 2023.11.01 12.56.40 | Verbose | Value     : application/json
VERBOSE: 2023.11.01 12.56.40 | Verbose | Parameter : Authorization
VERBOSE: 2023.11.01 12.56.40 | Verbose | Value     : Bearer 
***
LONG BEARER TOKEN
***
VERBOSE: 2023.11.01 12.56.40 | Verbose | Parameter : Headers
VERBOSE: 2023.11.01 12.56.40 | Verbose | Value     : System.Collections.Hashtable
VERBOSE: 2023.11.01 12.56.40 | Verbose | Parameter : URI
VERBOSE: 2023.11.01 12.56.40 | Verbose | Value     : https://graph.microsoft.com/v1.0/users/jussi.hietanen@mydomain.com/contactFolders/**folder_id**/contacts/
VERBOSE: DELETE with 0-byte payload
>> TerminatingError(Invoke-RestMethod): "Etäpalvelin palautti virheen: (405) Menetelmä ei ole sallittu."
PS>TerminatingError(): "Etäpalvelin palautti virheen: (405) Menetelmä ei ole sallittu."
PS>TerminatingError(): "Etäpalvelin palautti virheen: (405) Menetelmä ei ole sallittu."
```

So now I'm getting **405: Method Not Allowed** error

**Comment by jussihi** [comment]
When running in PowerShell 7, I still get errors but with more information this time:
```
VERBOSE: 2023.11.01 13.43.23 | Verbose | Parameter : URI
VERBOSE: 2023.11.01 13.43.23 | Verbose | Value     : https://graph.microsoft.com/v1.0/users/jussi.hietanen@mydomain.com/contactFolders/*contact_folder_id*/contacts/
VERBOSE: 2023.11.01 13.43.23 | Verbose | Parameter : Authorization
VERBOSE: 2023.11.01 13.43.23 | Verbose | Value     : Bearer 
***
BEARER
***
VERBOSE: 2023.11.01 13.43.23 | Verbose | Parameter : Content-Type
VERBOSE: 2023.11.01 13.43.23 | Verbose | Value     : application/json
VERBOSE: 2023.11.01 13.43.23 | Verbose | Parameter : Headers
VERBOSE: 2023.11.01 13.43.23 | Verbose | Value     : System.Collections.Hashtable
VERBOSE: 2023.11.01 13.43.23 | Verbose | Parameter : Method
VERBOSE: 2023.11.01 13.43.23 | Verbose | Value     : Delete
VERBOSE: HTTP/1.1 DELETE with 0-byte payload
VERBOSE: received -byte response of content type application/json
>> TerminatingError(Invoke-RestMethod): "{"error":{"code":"ErrorInvalidRequest","message":"The OData request is not supported."}}"
PS>TerminatingError(): "Response status code does not indicate success: 405 (Method Not Allowed)."
PS>TerminatingError(): "Response status code does not indicate success: 405 (Method Not Allowed)."
2023.11.01 13.43.23 | Error | Failed to remove contact
```

**Comment by JeshuaEdgar** [comment]
Thanks for all the logs and information. I will have a look this afternoon and delve into the Graph API's to see if anything has been updated. The folder behaviour is weird indeed, will have a look into that too.

> Seems like I've got it working (at least partially) after changing the hardcoded "Contacts" to Finnish "Kontaktit" in func_Get-ContactFolder.ps1:7 : $contactsFolder = "Kontaktit". However, it only seems to sync contacts starting from "T". I only get 50something contacts when I should get over 600.
Also, nordic letters such as Ä, Å, and Ö are not showing up properly.
I will see if I can find a way around these issues and come back to this issue.. 👍

Will have a look at these too if the contacts folders can be made variable. The contacts list should report more than 50, that is the default usually. Will keep you updated on the issue.

**Comment by jussihi** [comment]
Thank you! I went a bit deeper into the code (first time looking at PowerShell so sorry if I've misunderstood something), but it seems like the line 41 in `Module\Public\func_Sync-GALContacts.ps1` seems to be problematic:
```
$comparisson = Compare-Object -ReferenceObject ($contactsInFolder | Select-Object -ExcludeProperty id) -DifferenceObject ($ContactList | Where-Object { $_.displayName -in $contactsInFolder.displayName }) 
```
`$comparisson` variable seems to include a list of objects only containing `InputObject=; SideIndicator=<=` afterwards.

I first thought this was a PowerShell 5.1 "feature", since I stumbled across this Windows documentation page:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-object?view=powershell-7.3#-excludeproperty
>Beginning in PowerShell 6, it's no longer required to include the Property parameter for ExcludeProperty to work.

Then I figured that the `InputObject` actually carries the object data inside of it; with this information I was able to make deletion work;

In `Module\Public\func_Sync-GALContacts.ps1`,

1. modify line 41 to:
`$comparisson = Compare-Object -ReferenceObject $contactsInFolder -DifferenceObject ($ContactList | Where-Object { $_.displayName -in $contactsInFolder.displayName }) ` 
so that the ID is not removed and it carries over to the remove function
2. Modify the line 48's for each loop to:
`$removeContacts.InputObject | ForEach-Object { `
so that the contact objects are given to the remove function, not the comparison objects. InputObject is the object that has the ID inside of it.

Now I'm just not sure if this affects the rest of the code, so I will not create a PR from this hacky "patch".

**Comment by jussihi** [comment]
It also seems like there's something wrong with the `odata.nextLink` handling in `New-GraphRequest`. Sometimes I'm able to get _part of the very **end**_ of the GAL gathered (so only the last request? is added to the list), but sometimes `Get-GALContacts` return null; I.e., if I try to print out the list of Contact objects after line 9 in `Module\Public\func_Get-GALContacts.ps1`, I only get null.

Thank you already for your time. I've sponsored some coffee for you!

**Comment by JeshuaEdgar** [comment]
Thanks so much for the coffee, appreciate it!

I have just pushed a new version that fixes all the above except for the accented characters like mentioned in #4. Maybe for now swap it out for one of the Graph SDK cmdlets.

Let me know how you get on!

**Comment by jussihi** [comment]
I will check it tomorrow and report back how it works! Thanks a bunch in advance.

**Comment by jussihi** [comment]
@JeshuaEdgar , with a quick smoke test I still face some issues: After receiving contact list successfully, the code flow gets somehow confused after calling `Get-ContactFolder`. After the call, for example the value of `$contactFolder.mailBox` is `jussi.hietanen@mydomain.com jussi.hietanen@mydomain.com` and the contact folder name is also twice with a whitespace in between. This obviously ends up with an error. Here is a log snippet;

(See the last request's URI)

```
VERBOSE: 2023/11/02 19.11.22 | Verbose | Permissions are OK!
True
VERBOSE: 2023/11/02 19.11.22 | Verbose | Getting GAL contacts
VERBOSE: 2023/11/02 19.11.22 | Verbose | Parameter : URI
VERBOSE: 2023/11/02 19.11.22 | Verbose | Value     : https://graph.microsoft.com/beta/users?$select=*&$top=999
VERBOSE: 2023/11/02 19.11.22 | Verbose | Parameter : Method
VERBOSE: 2023/11/02 19.11.22 | Verbose | Value     : Get
VERBOSE: 2023/11/02 19.11.22 | Verbose | Parameter : Content-Type
VERBOSE: 2023/11/02 19.11.22 | Verbose | Value     : application/json
VERBOSE: 2023/11/02 19.11.22 | Verbose | Parameter : Authorization
VERBOSE: 2023/11/02 19.11.22 | Verbose | Value     : Bearer 
***
BEARER
***
VERBOSE: 2023/11/02 19.11.22 | Verbose | Parameter : Headers
VERBOSE: 2023/11/02 19.11.22 | Verbose | Value     : System.Collections.Hashtable
VERBOSE: HTTP/1.1 GET with 0-byte payload
VERBOSE: received -byte response of content type application/json
VERBOSE: Content encoding: utf-8
VERBOSE: 2023/11/02 19.11.26 | Verbose | 475 contacts found
2023/11/02 19.11.26 | Info | Beginning sync for jussi.hietanen@mydomain.com
VERBOSE: 2023/11/02 19.11.26 | Verbose | Getting folder syncedpeople
VERBOSE: 2023/11/02 19.11.26 | Verbose | Parameter : URI
VERBOSE: 2023/11/02 19.11.26 | Verbose | Value     : https://graph.microsoft.com/beta/users/jussi.hietanen@mydomain.com/contactFolders?$top=999
VERBOSE: 2023/11/02 19.11.26 | Verbose | Parameter : Method
VERBOSE: 2023/11/02 19.11.26 | Verbose | Value     : Get
VERBOSE: 2023/11/02 19.11.26 | Verbose | Parameter : Content-Type
VERBOSE: 2023/11/02 19.11.26 | Verbose | Value     : application/json
VERBOSE: 2023/11/02 19.11.26 | Verbose | Parameter : Authorization
VERBOSE: 2023/11/02 19.11.26 | Verbose | Value     : Bearer 
***
BEARER
***
VERBOSE: 2023/11/02 19.11.26 | Verbose | Parameter : Headers
VERBOSE: 2023/11/02 19.11.26 | Verbose | Value     : System.Collections.Hashtable
VERBOSE: HTTP/1.1 GET with 0-byte payload
VERBOSE: received -byte response of content type application/json
VERBOSE: Content encoding: utf-8
VERBOSE: 2023/11/02 19.11.26 | Verbose | Found folder syncedpeople, returning!
2023/11/02 19.11.26 | Info | Found folder syncedpeople for jussi.hietanen@mydomain.com
VERBOSE: 2023/11/02 19.11.26 | Verbose | Parameter : URI
VERBOSE: 2023/11/02 19.11.26 | Verbose | Value     : https://graph.microsoft.com/v1.0/users/jussi.hietanen@mydomain.com jussi.hietanen@mydomain.com/contactfolders/*folder_id* *folder_id again*/contacts?$top=999
VERBOSE: 2023/11/02 19.11.26 | Verbose | Parameter : Method
VERBOSE: 2023/11/02 19.11.26 | Verbose | Value     : Get
VERBOSE: 2023/11/02 19.11.26 | Verbose | Parameter : Content-Type
VERBOSE: 2023/11/02 19.11.26 | Verbose | Value     : application/json
VERBOSE: 2023/11/02 19.11.26 | Verbose | Parameter : Authorization
VERBOSE: 2023/11/02 19.11.26 | Verbose | Value     : Bearer 
***
BEARER
***
VERBOSE: 2023/11/02 19.11.26 | Verbose | Parameter : Headers
VERBOSE: 2023/11/02 19.11.26 | Verbose | Value     : System.Collections.Hashtable
VERBOSE: HTTP/1.1 GET with 0-byte payload
VERBOSE: received -byte response of content type application/json
>> TerminatingError(Invoke-RestMethod): "{"error":{"code":"ErrorInvalidUser","message":"The requested user 'jussi.hietanen@mydomain.com jussi.hietanen@mydomain.com' is invalid."}}"
```

I'm running this now on PowerShell 7

**Comment by JeshuaEdgar** [comment]
Hmmm I am not experiencing that behaviour. Are you running it through the bat file? Could you send that as a snippet? Thanks

**Comment by jussihi** [comment]
Yes here it is:

```
@echo off

pwsh.exe -ExecutionPolicy Bypass ^
-File "%CD%\Sync-Contacts.ps1" ^
-CredentialPath "%CD%\Credentials\credential.cred" ^
-Tenant "tenant_id" ^
-ContactFolderName "syncedpeople" ^
-LogPath "%CD%\Logs" ^
-Verbose ^
-MailboxList "jussi.hietanen@mydomain.com"
pause
```

I think there's nothing special about it apart from using PowerShell 7. `pwsh.exe` that I'm using is downloaded from Windows Store on Windows 11, version is currently 7.3.9

**Comment by jussihi** [comment]
Ah, it is of course because the `$folderList` has 2 objects inside the list. I will try to fix this issue now :)

**Comment by jussihi** [comment]
These issues are now fixed for me. There are still some minor bugs but I will open respective issues for those. Thanks for helping me out with these!
